# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jkiMndrQ6d60_VcimGlZKgRxuh_L9Iqf
"""

import pandas as pd
import seaborn as sns
import numpy as np
dataset1 = pd.read_csv('/content/2019-oct.csv')
dataset2 = pd.read_csv('/content/2019-nov.csv')
dataset3 = pd.read_csv('/content/2019-dec.csv')
dataset1

display(dataset1.shape,dataset2.shape,dataset3.shape)

merged_dataset = pd.concat([dataset1, dataset2, dataset3])
merged_dataset.shape

merged_dataset.head()

merged_dataset.describe()

merged_dataset.drop('Unnamed: 0',axis=1,inplace=True)

merged_dataset

merged_dataset.nunique()

merged_dataset['event_type'].unique()

merged_dataset['category_code'].unique()

merged_dataset.drop(['user_session','category_id','event_time','product_id','user_id'],axis=1,inplace=True)

merged_dataset

corelation = merged_dataset.corr()

sns.heatmap(corelation, xticklabels = corelation.columns, yticklabels = corelation.columns,annot = True)

sns.relplot(x = 'event_type', y = 'price', hue = 'category_code', data = merged_dataset)

sns.relplot(x = 'event_type', y = 'price', hue = 'brand', data = merged_dataset)

sns.distplot(merged_dataset['price'])

sns.catplot(x = 'price', kind = 'box', data = merged_dataset)

